# Generated by Django 4.0.3 on 2022-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_kategorije', models.CharField(help_text='Naziv Kategorije', max_length=200)),
            ],
        ),
    ]
