# Generated by Django 4.0.3 on 2022-03-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cms', '0004_kupci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kupci',
            old_name='address',
            new_name='adresa',
        ),
    ]
