# Generated by Django 4.0.3 on 2022-03-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potkategrije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_potkategrije', models.CharField(max_length=200)),
                ('opis', models.TextField(max_length=4000)),
                ('veza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_cms.kategorije')),
            ],
        ),
    ]
