# Generated by Django 4.0.3 on 2022-03-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cms', '0003_rename_potkategrije_potkategorije_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('primedba', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Kupci',
            },
        ),
    ]
